### ISSUE TITLE
implementation of TGAT

### ISSUE THREAD

**Issue by MrYaoH** [ckldan520/DDGCL#4]
Hi, author:
I have a question about your implementation of TGAT, i.e., the TGAT in your code seems different from the original TGAT. For example, the TGAT in your code process q, k, v after layer normalization while the original TGAT employs layer normalization after processing q, k, v. I don't know if I understand it right. Could you please answer my question?  Thank you!

**Comment by ckldan520** [comment]
Thank you very much for your detailed question. The original Transformer [Attention is all you need] employs layer-normalization after the attention calculation.  However, some articles [such as, On Layer Normalization in the Transformer Architectur] propose to employ layer-normalization before computing attention, because it helps the model converge faster. I understand that this will only affect the convergence speed of the model and will not lead to large differences in the final results. If you are interested in this, you can read the relevant literature, or try to do some verification experiments.

**Comment by MrYaoH** [comment]
> Thank you very much for your detailed question. The original Transformer [Attention is all you need] employs layer-normalization after the attention calculation. However, some articles [such as, On Layer Normalization in the Transformer Architectur] propose to employ layer-normalization before computing attention, because it helps the model converge faster. I understand that this will only affect the convergence speed of the model and will not lead to large differences in the final results. If you are interested in this, you can read the relevant literature, or try to do some verification experiments.

Thank you for your reply!
